Clean out unneeded files after docs merge
basetenlabs/truss pull request #1000
Opened 2024-06-25 01:53 UTC by philipkiely-baseten

## :rocket: What

Removes unneeded files after docs merge

2024-06-25 16:58 UTC, marius-baseten requested changes

2024-06-25 16:58 UTC, marius-baseten commented on docs/chains/doc_gen/generate_reference.py
Was this moved somewhere else?

2024-06-28 00:31 UTC, philipkiely-baseten commented on docs/chains/doc_gen/generate_reference.py
Oops, accidentally dropped this. Re-added!

2024-06-28 16:29 UTC, marius-baseten approved these changes

2024-06-28 16:29 UTC, marius-baseten commented on docs/chains/doc_gen/generate_reference.py
Cool, all good now. I think you can merge.

2024-06-28 23:22 UTC, merged