Serialize errors as bytes when necessary
basetenlabs/truss pull request #316
Opened 2023-06-01 21:48 UTC by spal1

We saw a couple of `unpack(b)` errors that came from the `proxy` endpoint when either a model isn't ready by `INFERENCE_SERVER_START_WAIT_SECS` or the inference server stopped running. This PR ensures that we serialize the error outputs correctly, based on the `request`'s headers.

2023-06-01 23:35 UTC, pankajroark approved these changes
Marking the tests as integration is important, lgtm otherwise. Thanks for getting to the root of this and fixing.

2023-06-01 23:35 UTC, pankajroark commented on truss/tests/templates/control/control/test_server.py
> +def test_patch_model_code_update_predict_model_not_ready(app, client):
We should definitely mark this as integration test as it could take a min.

2023-06-01 23:35 UTC, pankajroark commented on truss/tests/templates/control/control/test_server.py
> +def test_patch_model_code_update_predict_binary_model_not_ready(app, client):
Would be good to refactor to avoid duplication between the two tests.

2023-06-02 16:27 UTC, bolasim approved these changes
lgtm 
Thanks for doing this.

2023-06-02 16:35 UTC, joostinyi approved these changes

2023-06-09 18:25 UTC, bolasim requested changes
Marking to not merge as I am exploring a separate, more robust approach.

2023-06-13 06:50 UTC, bolasim commented
Closing in favor of https://github.com/basetenlabs/truss/pull/355. PTAL

2023-06-13 06:50 UTC, closed without merging