Proof of concept streaming in Truss.
basetenlabs/truss pull request #386
Opened 2023-06-26 13:47 UTC by squidarth

2023-06-27 20:00 UTC, pankajroark commented
About the single process for control server change. 

For the inference server we have a top level process and a worker:
https://github.com/basetenlabs/truss/blob/main/truss/templates/server/common/truss_server.py#L278
In practice, there’s only one worker, but we may have more in the future, and this is fine for the inference server.
The last attempt for control server move to FastApi has the same setup with a parent and a child process.
I think we don’t need this complex setup for the control server. A basic, single-process fastapi server is sufficient.

2023-07-03 16:40 UTC, bolasim approved these changes
lgtm. with some questions/suggestions.

would be great if @pankajroark also reviewed.

2023-07-03 16:40 UTC, bolasim commented on truss/templates/server/common/truss_server.py
> +            return StreamingResponse(response, media_type="application/octet-stream")
can you add a comment on how media type differs from content-type? That's the first thing that popped into my mind and i'm not sure if it conflates with the msgpack implementation

2023-07-03 16:40 UTC, bolasim commented on truss/tests/test_model_inference.py
> +        _ = tr.docker_run(local_port=8090, detach=True, wait_for_server_ready=False)
you can just set `wait_for_server_ready=True` or drop it from kwargs, then just jjump to the tests at 171. Adding the liveness/readiness probes here is not related to streaming and is test elsewhere.

2023-07-03 16:40 UTC, bolasim commented on truss/tests/test_model_inference.py
> +        invocations_response = requests.post(
s/invocations/predict/g for the rest of this test. invocations is a Sagemaker endpoint and we don't know if there are other intricacies to get Sagemaker to stream so this test can be a false positive in that case.

2023-07-03 18:25 UTC, pankajroark requested changes
That lock issue seems worth taking another look at.

2023-07-03 18:25 UTC, pankajroark commented on truss/test_data/test_streaming_truss/model/model.py
> +    def predict(self, model_input: Any) -> Dict[str, List]:
Return type

2023-07-03 18:25 UTC, pankajroark commented on truss/templates/server/common/truss_server.py
> +                headers={key.lower(): value for key, value in request.headers.items()},
minor: a transform_keys function is waiting to get out here. Could go into truss/util/data_structures

2023-07-03 18:25 UTC, pankajroark commented on truss/templates/server/model_wrapper.py
> +            locked_response_generator = _locked_response_generator(
There seems to be an issue. The predict call above will have finished and released the lock. There's a small chance that another request executes before the lock is acquired here. That other request could potentially end up using the gpu and affect this request. We may want to do this inside the predict function.

2023-07-04 05:55 UTC, squidarth commented on truss/templates/server/model_wrapper.py
> +            locked_response_generator = _locked_response_generator(
@pankajroark I tried a different approach here per our convo in Slack, curious what you think!

2023-07-06 06:51 UTC, pankajroark commented on truss/templates/server/model_wrapper.py
> +            locked_response_generator = _locked_response_generator(
What if the request is terminated suddenly and the streaming response is not completely read? Is it possible that the lock will never be release then?

2023-07-06 07:00 UTC, pankajroark commented on truss/templates/server/model_wrapper.py
> +            locked_response_generator = _locked_response_generator(
Indeed if a request never reads the full response then the server hangs there for a very long time. Depending on the client behavior is not safe. I've pushed a change to test_streaming_truss to illustrate this.

2023-07-06 09:29 UTC, squidarth commented on truss/templates/server/model_wrapper.py
> +            locked_response_generator = _locked_response_generator(
Yes, that's right. Hmm..

@pankajroark Great point. Thinking more on this, I think we should actually opt for a design that requires a bit more surgery:

In the streaming case, right now, we just pass the generator directly to the `StreamingResponse` object. What if instead, we consumed the stream and wrote the data to a threadsafe queue instead? Then, when it is done writing to the queue, it can relinquish the predict lock. The StreamingResponse takes a different generator, which just reads from the threadsafe queue instead. If the client stops reading, it's fine, because the predict lock is relinquished when the generation is done.

I can draw up a PoC of this approach

2023-07-07 06:10 UTC, pankajroark approved these changes

2023-07-07 06:34 UTC, merged