Infer dependencies based on what's imported into namespace
basetenlabs/truss pull request #77
Opened 2022-08-25 20:21 UTC by bolamalek

2022-08-25 20:22 UTC, bolamalek commented
@pankajroark just need some feedback on initial approach. Will revisit tests and dead code if I'm along the right path here

2022-08-25 22:40 UTC, pankajroark commented on truss/model_framework.py
> +    def requirements_txt(self, root_fn_name: str = "mk_truss") -> List[str]:
Would be good to add a doc comment explaining the root_fn_name parameter. It's also worth thinking about whether root_fn_name is a good parameter.

2022-08-25 22:41 UTC, pankajroark commented on truss/model_framework.py
> +    def required_depedencies(self) -> Set[str]:
Perhaps rename to `required_python_dependencies`?

2022-08-25 23:10 UTC, pankajroark requested changes
Seems worth exploring if we can avoid asking for root_fn_name. minor comments otherwise.

2022-08-25 23:10 UTC, pankajroark commented on truss/constants.py
> +SKLEARN_REQ_MODULE_NAME = {
plural, for all these constants.

2022-08-30 16:55 UTC, pankajroark approved these changes
lgtm, once tests pass.

2022-08-30 17:45 UTC, merged